#!/bin/bash
shell_dir="${HOME}/.config/shell.d"

if [[ -e "${shell_dir}/user" ]]; then
    source ${shell_dir}/user
fi

if [[ -e "${shell_dir}/aliases" ]]; then
    source ${shell_dir}/aliases
fi

if [[ -e "${shell_dir}/functions" ]]; then
    source ${shell_dir}/functions
fi

if [[ -e "${shell_dir}/startup" ]]; then
    source ${shell_dir}/startup
fi