#!/bin/bash
# Controls current music player
#
# $1 - The operation to perform (next, previous, play-pause)
# $? - Whether the operation was successful

source ./utils

if [[ ${#} -eq 0 ]]; then
	error "No arguments provided"
	exit 1
fi

for prog in "playerctl"; do
	if ! which ${prog} &>/dev/null; then
		error "${prog} is not installed"
		exit 1
	fi
done

while [[ ${#} -gt 0 ]]; do
	case "$1" in
		next|previous|play-pause)
			playerctl --player=mpd,spotify,firefox,%any "${1}"
			;;
		*)
			exit 1
			;;
	esac
	shift
done
