#!/bin/bash
# Sets or display volume of current sink
#
# $? - Whether the volume was displayed/updated

source ./utils

display_volume() {
	local muted="$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')"
	if [[ "$muted" = "yes" ]]; then
		echo "muted"
	else
		echo "$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | tr -d '[:space:]%')"
	fi
}

if [[ ${#} -eq 0 ]]; then
	exit -1
fi

for prog in "pactl"; do
	if ! which ${prog} &>/dev/null; then
		error "${prog} is not installed"
		exit 1
	fi
done

while [[ ${#} -gt 0 ]]; do
	case "$1" in
	inc)
		pactl set-sink-volume @DEFAULT_SINK@ +2%
		;;
	dec)
		pactl set-sink-volume @DEFAULT_SINK@ -2%
		;;
	toggle)
		pactl set-sink-mute @DEFAULT_SINK@ ${1}
		;;
	display)
		display_volume
		;;
	*)
		exit -1
		;;
	esac
	shift
done
