#!/bin/bash
# Pipes all sinks to dmenu and allows user to 
# select the current sink
#
# $? - If the sink was select or if there was an error

source ./utils

for prog in "jq" "pactl" "notify-send" "dmenu"; do
	if ! which ${prog} &>/dev/null; then
		error "${prog} not installed"
		exit 1
	fi
done

function get_sink_name() {
	if [ -z "$1" ]; then
		exit 1
	fi
	pactl --format=json list sinks \
		| jq -r --arg choice "$*" '.[]
			| select(.description == $choice)
			| .name
		'
}

function get_all_sinks() {
	pactl --format=json list sinks \
		| current=${default_sink} jq -r '.[]
			| if .name == env.current then
				.state="* "
			else
				.state=""
			end
			| .state + .description
		'
}

default_sink=$(pactl get-default-sink)

if
	! choice=$(printf '%s\n' "$(get_all_sinks)" \
		| sort \
		| dmenu -i -c -l 20 -p 'Sink: ' "$@");
then
	error "Could not parse sink choice"
	exit 1
fi

if [ -n "${choice}" ]; then
	if [ "${choice}" = "* ${default_sink}" ]; then
		exit 0
	fi
	pactl set-default-sink "$(get_sink_name ${choice})"
	notify-send "Sink is now: ${choice}"
else
	exit 0
fi
