#!/bin/bash
# Validates JSON with jq
#
# $1 - JSON file
# &0 - The JSON
# &? - Whether the JSON was valid or not

source ./utils

for prog in "jq"; do
	if ! which ${prog} &>/dev/null; then
		error "${prog} not installed"
		exit 1
	fi
done

if [[ -n "$1" ]]; then
	jq -c '.' "$1" &>/dev/null
else
	cat | jq -r '.' &>/dev/null
fi

exit $?