#!/bin/bash
# Install a python module
#
# $1 - The module to uninstall
# $? - Whether the module exists

source ./utils

for prog in "python3"; do
	if ! which ${prog} &>/dev/null; then
		error "${prog} not installed"
		exit 1
	fi
done

if ! printenv | grep -q VIRTUAL_ENV; then
	error "Not in a virtual environment"
	exit 1
fi

if [[ -z "${1}" ]]; then
	error "No module passed"
	exit 1
fi

pip uninstall "$1"