#!/bin/bash
# Useful utility functions common to all scripts

function info() {
	local color=$'\e[0;32m'
	local clear=$'\e[0m'

	if [[ -z "${1}" ]]; then
		exit 1
	fi
	
	echo "${color}Info${clear} ${1}"
}

function warning() {
	local color=$'\e[1;33m'
	local clear=$'\e[0m'

	if [[ -z "${1}" ]]; then
		exit 1
	fi
	
	echo "${color}Warning${clear} ${1}"
}

function error() {
	local color=$'\e[0;31m'
	local clear=$'\e[0m'

	if [[ -z "${1}" ]]; then
		exit 1
	fi
	
	echo "${color}Error${clear} ${1}"
}