#!/usr/bin/env bash

function l() {
  command eza \
    --color=auto \
    --long \
    --all \
    --header \
    "${1}"
}

function lt() {
  command eza \
    --color=auto \
    --tree \
    ${1}
}

function up() {
  local dirs
  [[ -z ${1} ]] && set -- 1
  for i in $(seq 1 ${1}); do dirs="../${dirs}"; done
  cd ${dirs}
}

# TODO: Test
function dif() { 
  command diff \
    --recursive \
    --unified \
    --color=always \
    "${@}" | command bat
}

function bt() {
  command bat \
    --color always \
    ${*}
}

function wbt() {
  command bat \
    --color always \
    --show-all \
    ${*}
}

function find_preview() {
  command find \
    ${@} \
    -exec \
    $(which bat) \
    {} +
}

function fzf() {
	set -Ux FZF_DEFAULT_OPTS "
		--color=fg:#908caa,bg:#191724,hl:#ebbcba
		--color=fg+:#e0def4,bg+:#26233a,hl+:#ebbcba
		--color=border:#403d52,header:#31748f,gutter:#191724
		--color=spinner:#f6c177,info:#9ccfd8,separator:#403d52
		--color=pointer:#c4a7e7,marker:#eb6f92,prompt:#908caa"
	command fzf
  
}

function bemenu() {
  bemenu-run \
    --fb "#1e1e2e" \
    --ff "#cdd6f4" \
    --nb "#1e1e2e" \
    --nf "#cdd6f4" \
    --tb "#1e1e2e" \
    --hb "#1e1e2e" \
    --tf "#f38ba8" \
    --hf "#f9e2af" \
    --af "#cdd6f4" \
    --ab "#1e1e2e"
}

# function ranger_cd() {
# }
