#!/bin/bash
# Useful utility functions common to all scripts

function info() {
	local color=$'\e[0;32m'
	local clear=$'\e[0m'

	if [[ -z "${1}" ]]; then
		return 1
	fi
	
	echo "${color}Info${clear} ${1}"
}

function warning() {
	local color=$'\e[1;33m'
	local clear=$'\e[0m'

	if [[ -z "${1}" ]]; then
		return 1
	fi
	
	echo "${color}Warning${clear} ${1}"
}

function error() {
	local color=$'\e[0;31m'
	local clear=$'\e[0m'

	if [[ -z "${1}" ]]; then
		return 1
	fi
	
	echo "${color}Error${clear} ${1}"
}

function verify_installed() {
	for command in $@; do
		if ! command -v "${command}" >/dev/null; then
			error "${command} not installed"
			return 1
		fi
	done
}

function is_url() {
	if [[ $# -ne 1 ]]; then
		error "Missing argument"
		return 1
	fi

	if ! echo "${1}" | grep -E '^^http[s]?:\/\/' >/dev/null; then
		return 1
	fi
}

