#!/bin/bash
## Update path with scripts and LSPs

export TERM=xterm-256color

if [[ -d "${HOME}/.local/bin" ]]; then
	export PATH="${HOME}/.local/bin:${PATH}"
fi

# Start MPD
if [[ ! -s ~/.config/mpd/pid ]]; then
	mpd
fi

if [[ -d "${HOME}/.cargo" ]]; then
	if [[ -e "${HOME}/.cargo/env" ]]; then
		source "${HOME}/.cargo/env"
	fi
fi

export HELIX_RUNTIME=/usr/lib/helix/runtime

eval "$(starship init bash)"
eval "$(zellij setup --generate-auto-start bash)"